### ISSUE TITLE
FAILED TRANSACCIONS

### ISSUE THREAD

**Issue by pedromaestu** [mintme-com/wallet#5]
*Github issues are primarily for reporting bugs or getting assistance with development-related items. If you have a question or need support with our product, please email support@mintme.com for faster attention.*

*If you are reporting an issue, please use the template below so we can reproduce, determine the cause of the issue, and fix it! If you are not reporting an issue, delete this entire thing and type away. Thanks!*

---

### Description of Issue

...

Status | FAILED(See more on MintMe Explorer)
-- | --
TX Hash | 0x56c3befefaca2e0f2206d648d68757addac0891f876a530668939925d7344678
Block Number | 4951992
Dirección de origen | 0x4fe7959E957DcCe477cCCB0F9fDDdd6650094F18
Dirección de destino | 0xfA244f323244fBBE63281dAd4B319F176CCfa6d7
Cantidad | 0 MINTME
Precio del gas | 200 Gwei
Límite de gas | 58783
Gas Used | 58324

### What exactly were you doing when you encountered this issue?

...Give us some steps to reproduce...

### How were you accessing your wallet?

Keystore File,.

### Description of Your Machine

- Browser: 
- Browser version:
- Operating system: WIN 10
- Device: PC
- MyCrypto.com vs Desktop Application? MINTME WALLET
- MyCrypto Version Number: 1.7.7.

### Console Logs / Screenshots

HELLO, I have a balance of 10,000 vigo tokens in the wallet that I want to send and it always fails, I have two other transitions in the history that appear but in the destination no, I still have another vigo token transaction to an Ether account but it does not appear in the destination I have tried the BAT with another specific token and I have sent and received without problems, I have no idea what can happen, have I lost the funds? you can check this thanks

...
![image](https://user-images.githubusercontent.com/34664089/87209509-7223d500-c312-11ea-9e8c-0adb16456229.png)

**Comment by danielwebimp** [comment]
@pedromaestu  In this case, gas should be set to 90001 or more and not 10000.  90001 is greater than 10000. This is applicable when you are sending tokens.
You can see transactions of your contract from the section Internal transaction on MintMe Explorer : https://www.mintme.com/explorer/addr/0xfa244f323244fbbe63281dad4b319f176ccfa6d7#tab_addr_2  : http://joxi.ru/4AkkZy4UXWlGNA
when you want to send your tokens, you should make sure you have also some MintMe in your wallet, because fees are applied in MintMe currency. If you don't have any MintMe in your wallet, the transaction will fail.
You can see your tokens from MintMe Explorer by clicking on the section Known ERC20 token transactions http://joxi.ru/4AkkZy4UXWlBNA : https://www.mintme.com/explorer/addr/0xc82b23d7f412384749850e92c7d74265e037c7b5#tab_addr_2
Let me know if you still have any issue after applying what I have mentioned previously.

> _Github issues are primarily for reporting bugs or getting assistance with development-related items. If you have a question or need support with our product, please email [support@mycrypto.com](mailto:support@mycrypto.com) for faster attention._
> 
> _If you are reporting an issue, please use the template below so we can reproduce, determine the cause of the issue, and fix it! If you are not reporting an issue, delete this entire thing and type away. Thanks!_
> 
> ### Description of Issue
> ...
> 
> Status	FAILED(See more on MintMe Explorer)
> TX Hash	0x56c3befefaca2e0f2206d648d68757addac0891f876a530668939925d7344678
> Block Number	4951992
> Dirección de origen	0x4fe7959E957DcCe477cCCB0F9fDDdd6650094F18
> Dirección de destino	0xfA244f323244fBBE63281dAd4B319F176CCfa6d7
> Cantidad	0 MINTME
> Precio del gas	200 Gwei
> Límite de gas	58783
> Gas Used	58324
> ### What exactly were you doing when you encountered this issue?
> ...Give us some steps to reproduce...
> 
> ### How were you accessing your wallet?
> Keystore File,.
> 
> ### Description of Your Machine
> * Browser:
> * Browser version:
> * Operating system: WIN 10
> * Device: PC
> * MyCrypto.com vs Desktop Application? MINTME WALLET
> * MyCrypto Version Number: 1.7.7.
> 
> ### Console Logs / Screenshots
> HELLO, I have a balance of 10,000 vigo tokens in the wallet that I want to send and it always fails, I have two other transitions in the history that appear but in the destination no, I still have another vigo token transaction to an Ether account but it does not appear in the destination I have tried the BAT with another specific token and I have sent and received without problems, I have no idea what can happen, have I lost the funds? you can check this thanks
> 
> ...
> ![image](https://user-images.githubusercontent.com/34664089/87209509-7223d500-c312-11ea-9e8c-0adb16456229.png)
