### ISSUE TITLE
i cannot able to login to my account using rapidminer alhub url so where can i find my url

### ISSUE THREAD

**Issue by arif627** [mintme-com/wallet#7]
*Github issues are primarily for reporting bugs or getting assistance with development-related items. If you have a question or need support with our product, please email support@mycrypto.com for faster attention.*

*If you are reporting an issue, please use the template below so we can reproduce, determine the cause of the issue, and fix it! If you are not reporting an issue, delete this entire thing and type away. Thanks!*

---

### Description of Issue

...

### What exactly were you doing when you encountered this issue?

...Give us some steps to reproduce...

### How were you accessing your wallet?

...Ledger, Trezor, MetaMask, Private Key, Keystore File, Parity Signer, Mnemonic Phrase?...

### Description of Your Machine

- Browser:
- Browser version:
- Operating system:
- Device:
- MyCrypto.com vs Desktop Application?
- MyCrypto Version Number:

### Console Logs / Screenshots

...

**Comment by danielwebimp** [comment]
> _Github issues are primarily for reporting bugs or getting assistance with development-related items. If you have a question or need support with our product, please email [support@mycrypto.com](mailto:support@mycrypto.com) for faster attention._
> 
> _If you are reporting an issue, please use the template below so we can reproduce, determine the cause of the issue, and fix it! If you are not reporting an issue, delete this entire thing and type away. Thanks!_
> 
> ### Description of Issue
> ...
> 
> ### What exactly were you doing when you encountered this issue?
> ...Give us some steps to reproduce...
> 
> ### How were you accessing your wallet?
> ...Ledger, Trezor, MetaMask, Private Key, Keystore File, Parity Signer, Mnemonic Phrase?...
> 
> ### Description of Your Machine
> * Browser:
> * Browser version:
> * Operating system:
> * Device:
> * MyCrypto.com vs Desktop Application?
> * MyCrypto Version Number:
> 
> ### Console Logs / Screenshots
> ...

Could tell me more about which links you are talking about? I think that question is not related to any issue concerning MintMe Wallet so I will close it if there is nothing more specific about MintMe wallet issue
