### ISSUE TITLE
i have withdrawal my fund to my mintme wallet but untill now i have not received my balance to the current address and hw can i exchange my mintme to another curency

### ISSUE THREAD

**Issue by arif627** [mintme-com/wallet#8]
*Github issues are primarily for reporting bugs or getting assistance with development-related items. If you have a question or need support with our product, please email support@mintme.com for faster attention.*

If you are reporting an issue, please use the template below so we can reproduce, determine the cause of the issue, and fix it! If you are not reporting an issue, delete this entire thing and type away. Thanks!

*If you are reporting an issue, please use the template below so we can reproduce, determine the cause of the issue, and fix it! If you are not reporting an issue, delete this entire thing and type away. Thanks!*

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by danielwebimp** [comment]
> _Github issues are primarily for reporting bugs or getting assistance with development-related items. If you have a question or need support with our product, please email [support@mintme.com](mailto:support@mintme.com) for faster attention._
> 
> If you are reporting an issue, please use the template below so we can reproduce, determine the cause of the issue, and fix it! If you are not reporting an issue, delete this entire thing and type away. Thanks!
> 
> _If you are reporting an issue, please use the template below so we can reproduce, determine the cause of the issue, and fix it! If you are not reporting an issue, delete this entire thing and type away. Thanks!_
> 
> **Describe the bug**
> A clear and concise description of what the bug is.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Go to '...'
> 2. Click on '....'
> 3. Scroll down to '....'
> 4. See error
> 
> **Expected behavior**
> A clear and concise description of what you expected to happen.
> 
> **Screenshots**
> If applicable, add screenshots to help explain your problem.
> 
> **Desktop (please complete the following information):**
> 
> * OS: [e.g. iOS]
> * Browser [e.g. chrome, safari]
> * Version [e.g. 22]
> 
> **Smartphone (please complete the following information):**
> 
> * Device: [e.g. iPhone6]
> * OS: [e.g. iOS8.1]
> * Browser [e.g. stock browser, safari]
> * Version [e.g. 22]
> 
> **Additional context**
> Add any other context about the problem here.

Hi, 
Could tell me from which site to which site you've tried to withdraw your coins and you weren't able?
If you've tried to withdraw your coins from Coinimp to MintMe Exchange or you have tried to send MintMe Coin from your personal desktop wallet to MintMe Exchange and it was less than 1 MintMe, then it's lost. Because the minimum deposit on MintMe Exchange is 1 MintMe Coin. 
If you are not yet using the desktop wallet, you can download the desktop wallet from here : https://github.com/mintme-com/wallet/releases/tag/v1.0.0 . Then when you are withdrawing from Coinimp.com website, send it to your personal desktop wallet. When it reaches more than 1 MintMe Coin, then you can send it to MintMe Exchange to exchange your MintMe Coin to BTC or to buy other tokens.

**Comment by danielwebimp** [comment]
Now to exchange your MintMe Coin to BTC, you should simply create a sell order of your MintMe Coin, as soon as someone buys your coins, you will immediately get your BTC.

**Comment by lockness-Ko** [comment]
> Now to exchange your MintMe Coin to BTC, you should simply create a sell order of your MintMe Coin, as soon as someone buys your coins, you will immediately get your BTC.

Hey, just a tip: please don't charge a shit ton of bitcoin to withdraw it??? It's really annoying and I reckon with the amount of users on your site you could do with taking less bitcoin
